# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import sys, os
from datetime import date

# -- Project information -----------------------------------------------------

project = 'Concordium'
copyright = f'2021 - {date.today().year}, Concordium Software ApS'
author = 'Concordium'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.graphviz",
    "sphinx.ext.intersphinx",
    "sphinx.ext.extlinks",
    "sphinx_reredirects",
    "sphinx_copybutton",
    "sphinx_toolbox.collapse",
    "sphinx_tabs.tabs",
    "sphinx_design",
    'notfound.extension',
    "sphinx_tippy",
    "sphinx_sitemap",
    "sphinxcontrib.video",
    'sphinx_selective_exclude.eager_only',
    'sphinx_selective_exclude.search_auto_exclude', 
    'sphinx_selective_exclude.modindex_exclude',
    'sphinxcontrib.mermaid'
]

# sphinx-prompt must be the first of these two.
extensions += ['sphinx-prompt', 'sphinx_substitution_extensions']

extlinks = {
    'cdw-pubkey': ('https://distribution.mainnet.concordium.com/tools/concordium-desktop-wallet-pubkey.pem?%s', 'Download public key:%s'),
    'cdw-sig': ('https://distribution.mainnet.concordium.software/tools/linux/concordium-desktop-wallet-1.7.4.%s.sig', 'Download signature:%s') # Supply extension, e.g. exe, dmg, AppImage
}

# todo_include_todos = True
# todo_emit_warnings = True
# todo_link_only = True

# sitemap config
html_baseurl = "https://docs.concordium.com/en/mainnet/"
sitemap_url_scheme = "{link}"
sitemap_locales = [None]

graphviz_fontname = "'Lato,proxima-nova,Helvetica Neue,Arial,sans-serif'"

graphviz_output_format="svg"
graphviz_dot_args=[
    "-Gfontname="+graphviz_fontname,
    "-Gfontsize=12",
    "-Gbgcolor=transparent",
    "-Nfontname="+graphviz_fontname,
    "-Nfontsize=12",
    "-Efontname="+graphviz_fontname,
    "-Efontsize=12",
]
# Options for copybutton behavior
copybutton_prompt_text = "$"
copybutton_line_continuation_character = "\\"

# Options for tabs behavior
sphinx_tabs_disable_tab_closing = True

# Disable default url prefix "/en/latest/" on every resource.
notfound_urls_prefix = "/en/mainnet/"

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates', '../_templates']

# 404 page template.
notfound_template = '404.html'

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx" #"friendly" # "sphinx" # "lovelace" # None # "abap" # "sas" # "algol_nu"
highlight_language = "rust"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"

html_logo = "../_static/concordium-logo.svg"
html_favicon = "../_static/concordium-logo-no-text.svg"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# These options are for pydata_sphinx_theme
html_theme_options = {
    # 'canonical_url': '',
    # 'analytics_id': 'UA-XXXXXXX-1',  #  Provided by Google in your dashboard
    # 'analytics_anonymize_ip': False,
    # 'logo_only': True,
    # 'display_version': True,
    # 'prev_next_buttons_location': None,
    # 'style_external_links': False,
    # 'style_nav_header_background': '#235c9b',
    "use_edit_page_button": True,
    # # Toc options
    "collapse_navigation": False,
    # 'sticky_navigation': True,
    # 'includehidden': False,
    "navigation_with_keys": False,
    # 'titles_only': False,
    "show_nav_level": 1,
    "show_toc_level": 2,
    "navigation_depth": 5,
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end": ["navbar-icon-links", "theme-switcher"],
    "secondary_sidebar_items": ["page-toc", "edit-this-page"],
    "article_footer_items": ["footer-article"],
    "show_prev_next": True,
    #"navbar_align": "left",
    "icon_links": [
        {
            # Concordium GitHub
            "name": "GitHub",
            # URL where the link will redirect
            "url": "https://github.com/Concordium",  # required
            # Icon class (if "type": "fontawesome"), or path to local image (if "type": "local")
            "icon": "fab fa-github-square",
            # Whether icon should be a FontAwesome class, or a local file
            "type": "fontawesome",  # Default is fontawesome
            # Add additional attributes to the href link.
            # The defaults of the target, rel, class, title, and href may be overwritten.
            "attributes": {
               "target" : "_blank",}
        },
        {
            # Concordium Email Support
            "name": "Support",
            # URL where the link will redirect
            "url": "mailto:support@concordium.software",  # required
            # Icon class (if "type": "fontawesome"), or path to local image (if "type": "local")
            "icon": "fas fa-envelope",
            # Whether icon should be a FontAwesome class, or a local file
            "type": "fontawesome",  # Default is fontawesome
            # Add additional attributes to the href link.
            # The defaults of the target, rel, class, title, and href may be overwritten.
            "attributes": {
               "target" : "_blank",}
        },
        {
            # Concordium monitoring options
            "name": "Monitor",
            # URL where the link will redirect
            "url": "https://ccdscan.io",  # required
            # Icon class (if "type": "fontawesome"), or path to local image (if "type": "local")
            "icon": "fas fa-chart-line",
            # Whether icon should be a FontAwesome class, or a local file
            "type": "fontawesome",  # Default is fontawesome
            # Add additional attributes to the href link.
            # The defaults of the target, rel, class, title, and href may be overwritten.
            "attributes": {
               "target" : "_blank",}
        },
        {
            "name": "Discourse",
            "url": "https://support.concordium.software/latest",
            "icon": "fab fa-discourse",
            "type": "fontawesome",
            # Add additional attributes to the href link.
            # The defaults of the target, rel, class, title, and href may be overwritten.
            "attributes": {
               "target" : "_blank",}
        },
        {
            # Concordium Discord
            "name": "Discord",
            # URL where the link will redirect
            "url": "https://discord.com/invite/GpKGE2hCFx",
            # Icon class for Discord using FontAwesome
            "icon": "fab fa-discord",
            # Using FontAwesome
            "type": "fontawesome",
            # Opening in a new tab
            "attributes": {
            "target": "_blank",
            }
        },
        {
            "name": "YouTube",
            "url": "https://www.youtube.com/channel/UCPZc2CuB2jGbZjD_5zX7-1A",
            "icon": "fab fa-youtube",
            "type": "fontawesome",
            # Add additional attributes to the href link.
            # The defaults of the target, rel, class, title, and href may be overwritten.
            "attributes": {
               "target" : "_blank",}
        },
        {
            "name": "Medium",
            "url": "https://medium.com/@concordium",
            "icon": "fab fa-medium",
            "type": "fontawesome",
            # Add additional attributes to the href link.
            # The defaults of the target, rel, class, title, and href may be overwritten.
            "attributes": {
               "target" : "_blank",}
        },
    ]
    }

html_show_sourcelink = False

html_context = {
    # "display_github": True,
    "github_user": "Concordium",
    "github_repo": "concordium.github.io",
    "github_version": "main",
    "doc_path": "source/mainnet",
    "conf_py_path": "/source/",
    "default_mode": "auto",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["../_static"]

html_css_files = [
    "css/custom.css",
    "css/tippy.css",
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
html_sidebars = {
    "**": ["sidebar-nav-bs"]
}

# html_additional_pages = {}

# Tippy configuration
tippy_js = ("https://unpkg.com/@popperjs/core@2", "https://unpkg.com/tippy.js@6")
tippy_skip_urls = [
    "(?!.*glossary.html.*)"
]
tippy_anchor_parent_selector = "article.bd-article"

# -- Options for linkchecking -------------------------------------------------

linkcheck_ignore = [r'https://fuchsia.googlesource.com/.+/', r'https://github.com/iqlusioninc/crates/tree/develop/zeroize_derive']
linkcheck_workers = 1
linkcheck_retries = 2
linkcheck_request_headers = {
    "https://crates.io/": {
        "Accept": "text/html",
        "Accept-Encoding": "utf-8",
    }
}

# -- InterSphinx links for linking between document versions ------------------
# intersphinx_mapping = {'smart-contracts-v0': ('https://developer.concordium.software/en/smart-contracts-v0/', None)}


# -- Sphinx-reredirects for redirecting old paths to new ones ----------------
redirects = {
    "learn/governance/index": "/learn/governance/gc-voting.html",
    "docs/index": "/index.html",
    "./net/guides/shielded-transfer": "/net/guides/shield-ccd-wallets.html",
    "./net/desktop-wallet/send-gtu-single-desktop": "/net/guides/send-ccd-wallets.html",
    "./net/desktop-wallet/shield-gtu-desktop": "/net/guides/shield-ccd-wallets.html",
    "./net/resources/terms-and-conditions-bw": "/net/resources/terms-and-conditions.html",
    "./net/resources/terms-and-conditions-mw-gen2": "/net/resources/terms-and-conditions.html",
    "./net/desktop-wallet/add-baker-pool-dw": "/net/mobile-wallet/add-baker-mw.html",
    "./net/concepts/concepts-backup": "/net/guides/recovery.html",
    "./net/resources/sirius-testnet-reset": "/index.html",
    "./net/resources/sirius-testnet-reset-wallets": "/index.html",
    "./net/resources/sirius-testnet-reset-client": "/index.html",
    "./net/resources/sirius-testnet-reset-nodes": "/index.html",
    "./en/mainnet/smart-contracts/index": "/smart-contracts/general/introduction.html",
    "./net/resources/release-notes": "net/release-notes/release-notes-lp.html",
    "./net/resources/release-notes-mainnet": "net/release-notes/release-notes-lp.html",
    "./en/mainnet/smart-contracts/tutorials/piggy-bank/preparing": "/smart-contracts/tutorials/piggy-bank/index.html",
    "./en/mainnet/smart-contracts/tutorials/nft-minting/setup-dev-env": "/smart-contracts/tutorials/setup-env.html",
    "./net/guides/overview-baker-process": "/net/concepts/concepts-baker.html",
    "./en/testnet4/index": "/index.html",
    "./en/testnet4/smart-contracts/index": "/index.html",
    "./en/testnet4/testnet/guides/accounts-transactions": "/index.html",
    "./en/testnet4/testnet/guides/explore-more": "/index.html",
    "./en/testnet4/testnet/guides/run-node": "/index.html",
    "./en/testnet4/testnet/references/concordium-client": "/index.html",
    "./en/testnet4/testnet/references/manage-accounts": "/index.html",
    "./en/testnet4/testnet/references/transactions": "/index.html",
    "./en/testnet4/testnet/see-also/downloads": "/index.html",
    "./en/testnet/net/concepts/concepts": "/guides/learn-about-concordium.html",
    "./en/testnet/net/desktop-wallet/change-restake-settings": "/net/mobile-wallet/update-baker-mw.html#update-baker-stake-and-restaking-preference",
    "./en/testnet/net/desktop-wallet/setup-maintenance-dw": "net/guides/overview-desktop.html",
    "./en/testnet/net/guides/run-node-macos": "net/guides/run-node-macos.html",
    "./en/testnet/net/references/developer-tools": "net/references/developer-tools.html",
    "./en/testnet/net/references/manage-accounts": "net/references/manage-accounts.html",
    "./en/testnet/smart-contracts/guides/deploy-module": "/smart-contracts/guides/deploy-module.html",
    "./net/browser-wallet/index": "net/browser-wallet/setup-browser-wallet.html",
    "./net/desktop-wallet/remove-baker": "net/mobile-wallet/update-baker-mw.html#stop-baking",
    "./net/mobile-wallet-gen2/index": "net/mobile-wallet-gen2/setup-mobile-wallet.html",
    "./net/mobile-wallet/baker-mw": "net/mobile-wallet/add-baker-mw.html",
    "./net/mobile-wallet/create-identity": "net/guides/create-identity.html",
    "./net/mobile-wallet/explore-more": "net/mobile-wallet-gen2/faq.html",
    "./net/mobile-wallet/export-import-mw": "net/guides/export-import.html",
    "./net/mobile-wallet/make-shielded-transfer-mw": "net/guides/shielded-transfer.html",
    "./net/mobile-wallet/make-simple-transfer-mw": "net/guides/send-ccd-wallets.html",
    "./net/mobile-wallet/setup-maintenance-mw": "net/mobile-wallet-gen2/setup-mobile-wallet.html",
    "./net/mobile-wallet/shield-unshield-mw": "net/guides/shield-ccd-wallets.html",
    "./classes/Common_GRPC_Client.ConcordiumGRPCClient": "concordium-node-sdk-js/classes/Common_GRPC_Client.ConcordiumGRPCClient.html",
    "./en/mainnet/index.html-": "/index.html",
    "./net/guides/delegation": "net/concepts/concepts-delegation.html",
    "./net/desktop-wallet/account-recovery": "/net/guides/recovery.html",
    "./net/desktop-wallet/change-baker-stake": "/net/mobile-wallet/update-baker-mw.html#update-baker-stake-and-restaking-preference",
    "./net/desktop-wallet/create-account-desktop": "net/guides/create-account.html",
    "./net/desktop-wallet/delegation-dw": "net/guides/add-delegation.html",
    "./net/desktop-wallet/get-started-desktop": "net/desktop-wallet/accounts-desktop.html",
    "./net/desktop-wallet/index": "net/guides/overview-desktop.html",
    "./net/desktop-wallet/make-account-report": "net/guides/transaction-report.html",
    "./net/desktop-wallet/send-shielded-amount": "net/guides/shielded-transfer.html",
    "./net/desktop-wallet/shield-ccd-desktop": "net/guides/shield-ccd-wallets.html",
    "./net/desktop-wallet/transfers-dw": "net/guides/send-ccd-wallets.html",
    "./net/desktop-wallet/update-baker-keys": "https://developer.concordium.software/en/mainnet/net/mobile-wallet/update-baker-mw.html#update-baker-keys",
    "./net/desktop-wallet/update-baker-pool-dw": "https://developer.concordium.software/en/mainnet/net/mobile-wallet/update-baker-mw.html#update-pool-settings",
    "./net/desktop-wallet/update-delegation": "net/guides/update-delegation.html",
    "./net/guides/add-baker-desktop": "net/mobile-wallet/add-baker-mw.html",
    "./net/guides/concordium-client": "net/references/concordium-client.html",
    "./net/installation/downloads-testnet": "net/installation/downloads.html",
    "./net/resources/legal": "net/resources/terms-and-conditions.html",
    "./en/mainnet/smart-contracts/onboarding-guide-solana-developers/index": "/smart-contracts/onboarding-guide-solana-developers/overview.html",
    "./net/references/grpc": "net/references/grpc2.html",
    "./en/mainnet/smart-contracts/guides/contract-testing-guides": "/smart-contracts/guides/integration-test-contract",
    "./en/mainnet/smart-contracts/best-practices/index": "/smart-contracts/best-practices/development",
    "net/smart-contracts/guides/quick-start": "/docs/smart-contracts/guides/quickstart.html",
    "net/smart-contracts/guides/deploy-module": "/how-to/smart-contracts/deploy-module.html",
    "net/concepts/id-accounts": "/docs/protocol/id-accounts.html",
    "net/smart-contracts/general/introduction": "/learn/smart-contracts/index.html",
    "net/smart-contracts/general/contract-instances": "/learn/smart-contracts/contract-instances.html",
    "net/smart-contracts/general/contract-lifecycle": "/learn/smart-contracts/contract-lifecycle.html",
    "net/smart-contracts/general/contract-module": "/learn/smart-contracts/contract-module.html",
    "net/smart-contracts/general/contract-schema": "/learn/smart-contracts/contract-schema.html",
    "net/smart-contracts/general/develop-contracts": "/learn/smart-contracts/develop-contracts.html",
    "net/smart-contracts/general/images/smart-contract-lifecycle.png": "/docs/smart-contracts/images/smart-contract-lifecycle.png",
    "net/references/manage-accounts": "/docs/protocol/manage-accounts.html",
    "net/images/concepts/account-creation.png": "/docs/protocol/images/account-creation.png",
    "net/smart-contracts/guides/setup-tools": "/how-to/smart-contracts/build-contract.html",
    "net/smart-contracts/guides/setup-contract": "/docs/smart-contracts/guides/setup-contract.html",
    "net/smart-contracts/guides/compile-module": "/docs/smart-contracts/guides/compile-module.html",
    "net/smart-contracts/guides/build-schema": "/docs/smart-contracts/guides/build-schema.html",
    "net/smart-contracts/guides/no-std": "/docs/smart-contracts/guides/no-std.html",
    "net/smart-contracts/guides/fallback-entrypoints": "/docs/smart-contracts/guides/fallback-entrypoints.html",
    "net/smart-contracts/guides/upgradeable-contract": "/docs/smart-contracts/guides/upgradeable-contract.html",
    "net/smart-contracts/guides/json-params": "/how-to/smart-contracts/json-params.html",
    "net/smart-contracts/guides/factory-pattern": "/how-to/smart-contracts/factory-pattern.html",
    "net/smart-contracts/guides/unit-test-contract": "/docs/smart-contracts/guides/unit-test-contract.html",
    "net/smart-contracts/guides/development": "/docs/smart-contracts/guides/development.html",
    "net/smart-contracts/guides/costs": "/docs/smart-contracts/guides/costs.html",
    "net/guides/company-identities": "/docs/protocol/company-identities.html",
    "net/images/company-id-request.png": "/docs/protocol/images/company-id-request.png",
    "net/images/company-id-create.png": "/docs/protocol/images/company-id-create.png",
    "net/images/company-id-acct-keys.png": "/docs/protocol/images/company-id-acct-keys.png",
    "net/images/company-id-recover.png": "/docs/protocol/images/company-id-recover.png",
    "net/concepts/concepts-transactions": "/docs/protocol/concepts-transactions.html",
    "net/concepts/concepts-baker": "/docs/protocol/concepts-baker.html",
    "net/concepts/concepts-delegation": "/docs/protocol/concepts-delegation.html",
    "net/images/concepts/baker-process1.png": "/docs/protocol/images/baker-process1.png",
    "net/images/concepts/baker-process2.png": "/docs/protocol/images/baker-process2.png",
    "net/smart-contracts/guides/initialize-contract": "/how-to/smart-contracts/initialize-contract.html",
    "net/smart-contracts/guides/interact-instance": "/how-to/smart-contracts/interact-instance.html",
    "net/smart-contracts/guides/inspect-instance": "/how-to/smart-contracts/inspect-instance.html",
    "net/smart-contracts/guides/invoke-instance": "/how-to/smart-contracts/invoke-instance.html",
    "net/guides/baker-pool": "/docs/network/baker-pool.html",
    "net/guides/baker-windows": "/docs/network/import-validator-keys.html",
    "net/nodes/baker-macos": "/docs/network/guides/import-validator-keys.html",
    "net/nodes/baker-ubuntu": "/docs/network/guides/import-validator-keys.html",
    "net/nodes/baker-docker": "/docs/network/guides/import-validator-keys.html",
    "net/guides/become-baker": "/docs/network/guides/become-baker.html",
    "net/references/concordium-client": "/technical-reference/concordium-client/concordium-client.html",
    "net/references/transactions": "/docs/protocol/manage-accounts.html#account-aliases",
    "net/references/query-node": "/technical-reference/concordium-client/query-node.html",
    "net/references/multi-sig": "/technical-reference/concordium-client/multi-sig.html",
    "net/web3-id/index": "/docs/network/web3-id/index.html",
    "net/web3-id/wallet": "/docs/network/web3-id/wallet.html",
    "net/web3-id/issuer": "/docs/network/web3-id/issuer.html",
    "net/guides/create-proofs": "/docs/network/guides/create-proofs.html",
    "net/web3-id/concordia": "/docs/network/web3-id/concordia.html",
    "net/guides/run-local-chain": "/docs/network/guides/run-local-chain.html",
    "net/guides/low-code-nft-marketplace/introduction": "/tutorials/low-code-nft-marketplace/introduction.html",
    "net/guides/low-code-nft-marketplace/marketplace": "/tutorials/low-code-nft-marketplace/marketplace.html",
    "net/guides/low-code-nft-marketplace/minting-tool": "/tutorials/low-code-nft-marketplace/minting-tool.html",
    "net/indexers/intro": "/docs/network/indexers/intro.html",
    "net/indexers/suoquery": "/docs/network/indexers/subquery.html",
    "net/nodes/node-requirements": "/docs/network/nodes/node-requirements.html",
    "net/guides/run-node-ubuntu": "/docs/network/nodes/run-node-ubuntu.html",
    "net/nodes/run-node-ubuntu": "/docs/network/nodes/run-node-ubuntu-testnet.html",
    "net/nodes/troubleshoot-ubuntu": "/docs/network/nodes/troubleshoot-ubuntu.html",
    "net/guides/run-node-macos": "/docs/network/nodes/run-node-macos.html",
    "net/nodes/troubleshoot-macos": "/docs/network/nodes/troubleshoot-macos.html",
    "net/guides/run-nodes-windows": "/docs/network/nodes/rin-nodes-windows.html",
    "net/nodes/node-runner-servide-configuration": "/docs/network/nodes/node-runner-service-configuration.html",
    "net/nodes/troubleshoot-windows": "/docs/network/nodes/troubleshoot-windows.html",
    "net/guides/run-node": "/docs/network/nodes/run-node.html",
    "net/nodes/troubleshoot-docker": "/docs/network/nodes/troubleshoot-docker.html",
    "net/nodes/ubuntu": "/docs/network/nodes/run-node-ubuntu.html",
    "net/nodes/macos": "/docs/network/nodes/run-node-macos.html",
    "net/nodes/windows": "/docs/network/nodes/run-node-windows.html",
    "net/nodes/docker": "/docs/network/nodes/run-node.html",
    "net/release-notes/release-notes-lp": "/docs/release-notes/release-notes-lp.html",
    "net/release-notes/release-notes-mainnet": "/docs/release-notes/release-notes-mainnet.html",
    "net/release-notes/release-notes": "/docs/release-notes/release-notes.html",
    "net/installation/downloads": "/docs/installation/downloads.html",
    "net/installation/previous-node-downloads": "/docs/installation/previous-node-downloads.html",
    "net/installation/verification-instructuions": "/docs/installation/verification-instructions.html",
    "net/installation/cargo-verification-instructions/cargo-linux": "/docs/installation/cargo-verification-instructions/cargo-linux.html",
    "net/installation/cdw-verification-instructions/cdw-appimage": "/docs/installation/cdw-verification-instructions/cdw-appimage.html",
    "net/installation/cdw-verification-instructions/cdw-deb": "/docs/installation/cdw-verification-instructions/cdw-deb.html",
    "net/installation/cdw-verification-instructions/cdw-rpm": "/docs/installation/cdw-verification-instructions/cdw-rpm.html",
    "net/installation/client-verification-instructions/client-linux": "/docs/installation/client-verification-instructions/client-linux.html",
    "net/installation/snippets/delegation-faq": "/docs/help/delegation-faq.html",
    "net/resources/glossary": "/docs/resources/glossary.html",
    "en/mainnet/smart-contracts/onboarding-guide-solana-developers/faq": "/docs/help-and-faq/onboarding-guide-solana-developers/faq.html",
    "en/mainnet/smart-contracts/onboarding-guide-solana-developers/overview": "/docs/help-and-faq/onboarding-guide-solana-developers/overview.html",
    "en/mainnet/smart-contracts/onboarding-guide-ethereum-developers/faq": "/docs/help-and-faq/onboarding-guide-ethereum-developers/faq.html",
    "net/voting/coordinator": "/docs/voting/coordinator.html",
    "net/voting/gc-voting": "/docs/voting/gc-voting.html",
    "net/voting/voting": "/docs/voting/voting.html",
    "net/voting/guardians": "/docs/voting/guardians.html",
    "net/voting/verify-election-result": "/docs/voting/verify-election-result.html",
    #"./en/mainnet/smart-contracts/tutorials/index": "/tutorials/smart-contract-tutorials.html", Comment for a hotfix test
    "smart-contracts/tutorials/setup-env": "/tutorials/setup-env.html",
    "smart-contracts/tutorials/counter/counter-contract": "/tutorials/counter/counter-contract",
    "smart-contracts/tutorials/piggy-bank/index": "/tutorials/piggy-bank/index.html",#changed by tkt
    "smart-contracts/tutorials/piggy-bank/writing": "/tutorials/piggy-bank/writing.html",
    "smart-contracts/tutorials/piggy-bank/testing": "/tutorials/piggy-bank/testing.html",
    "smart-contracts/tutorials/piggy-bank/deploying": "/tutorials/piggy-bank/deploying.html",
    "smart-contracts/tutorials/piggy-bank/frontend": "/tutorials/piggy-bank/frontend.html",
    "smart-contracts/tutorials/wCCD/index": "/tutorials/wCCD/index.html",
    "smart-contracts/tutorials/wCCD/wCCD-introduction": "/tutorials/wCCD/wCCD-introduction.html",
    "smart-contracts/tutorials/wCCD/wCCD-interacting": "/tutorials/wCCD/wCCD-interacting.html",
    "smart-contracts/tutorials/wCCD/wCCD-frontend_set_up": "/tutorials/wCCD/wCCD-frontend-set-up.html",
    "smart-contracts/tutorials/voting/index": "/tutorials/voting/index.html",
    "smart-contracts/tutorials/voting/voting-sc": "/tutorials/voting/voting-sc.html",
    "smart-contracts/tutorials/voting/voting-dapp": "/tutorials/voting/voting-dapp.html",
    "smart-contracts/tutorials/nft-minting/index": "/tutorials/nft-minting/index.html",
    "smart-contracts/tutorials/nft-minting/upload": "/tutorials/nft-minting/upload.html",
    "smart-contracts/tutorials/nft-minting/build-smart-contract": "/tutorials/nft-minting/build-smart-contract.html",
    "smart-contracts/tutorials/nft-minting/mint-xfer": "/tutorials/nft-minting/mint-xfer.html",
    "smart-contracts/tutorials/sft-minting/index": "/tutorials/sft-minting/index.html",
    "smart-contracts/tutorials/sft-minting/build-smart-contract": "/tutorials/sft-minting/build-smart-contract.html",
    "smart-contracts/tutorials/sft-minting/mint-xfer": "/tutorials/sft-minting/mint-xfer.html",
    "smart-contracts/tutorials/fungible-tokens/index": "/tutorials/fungible-tokens/index.html",
    "smart-contracts/tutorials/fungible-tokens/smart-contract": "/tutorials/fungible-tokens/smart-contract.html",
    "smart-contracts/tutorials/fungible-tokens/mint-xfer": "/tutorials/fungible-tokens/mint-xfer.html",
    "smart-contracts/tutorials/eSealing/index": "/tutorials/eSealing/index.html",
    "smart-contracts/tutorials/eSealing/eSealing-dapp": "/tutorials/eSealing/eSealing-dapp.html",
    "smart-contracts/tutorials/sponsoredTransactions/index": "/tutorials/sponsoredTransactions/index.html",
    "smart-contracts/tutorials/sponsoredTransactions/sponsoredTransactionsSmartContract": "/tutorials/sponsoredTransactions/sponsoredTransactionsSmartContract.html",
    "smart-contracts/tutorials/sponsoredTransactions/sponsoredTransactionsFrontendAndBackend": "/tutorials/sponsoredTransactions/sponsoredTransactionsFrontendAndBackend.html",
    "smart-contracts/tutorials/smartContractUpgrade/index": "/tutorials/smartContractUpgrade/index.html",
    "smart-contracts/tutorials/smartContractUpgrade/smartContractUpgrade": "/tutorials/smartContractUpgrade/smartContractUpgrade.html",
    "net/resources/ccd-scan": "/technical-reference/ccd-scan/ccd-scan.html",
    "net/resources/ccd-scan-accounts": "/technical-reference/ccd-scan/ccd-scan-accounts.html",
    "net/resources/ccd-scan-blocks": "/technical-reference/ccd-scan/ccd-scan-blocks.html",
    "net/resources/ccd-scan-nodes": "/technical-reference/ccd-scan/ccd-scan-nodes.html",
    "net/resources/ccd-scan-staking": "/technical-reference/ccd-scan/ccd-scan-staking.html",
    "net/resources/ccd-scan-transactions": "/technical-reference/ccd-scan/ccd-scan-transactions.html",
    "net/guides/sdks-apis": "/technical-reference/sdks.html",
    "net/references/grcp2": "/technical-reference/api.html",
    "net/guides/wallet-sdk/wallet-sdk": "/how-to/integrations/wallet-sdk/wallet-sdk.html",
    "net/guides/wallet-sdk/wallet-sdk-identity-creation": "/how-to/integrations/wallet-sdk/wallet-sdk-identity-creation.html",
    "net/guides/wallet-sdk/wallet-sdk-identity-recovery": "/how-to/integrations/wallet-sdk/wallet-sdk-identity-recovery.html",
    "net/guides/wallet-sdk/wallet-sdk-credential-deployment": "/how-to/integrations/wallet-sdk/wallet-sdk-credential-deployment.html",
    "net/guides/wallet-sdk/wallet-sdk-account-transaction": "/how-to/integrations/wallet-sdk/wallet-sdk-account-transaction.html",
    "net/guides/wallet-sdk/wallet-sdk-identity-provider": "/how-to/integrations/wallet-sdk/wallet-sdk-identity-provider.html",
    "tools/wallet-sdk/wallet-sdk": "/how-to/integrations/wallet-sdk/wallet-sdk.html",
    "tools/wallet-sdk/wallet-sdk-identity-creation": "/how-to/integrations/wallet-sdk/wallet-sdk-identity-creation.html",
    "tools/wallet-sdk/wallet-sdk-identity-recovery": "/how-to/integrations/wallet-sdk/wallet-sdk-identity-recovery.html",
    "tools/wallet-sdk/wallet-sdk-credential-deployment": "/how-to/integrations/wallet-sdk/wallet-sdk-credential-deployment.html",
    "tools/wallet-sdk/wallet-sdk-account-transaction": "/how-to/integrations/wallet-sdk/wallet-sdk-account-transaction.html",
    "tools/wallet-sdk/wallet-sdk-identity-provider": "/how-to/integrations/wallet-sdk/wallet-sdk-identity-provider.html",
    "tools/index": "/technical-reference/index.html",
    "tools/developer-page": "/technical-reference/index.html",
    "tools/sdks-apis": "/technical-reference/sdks.html",
    "docs/smart-contracts/references/index": "/technical-reference/index.html",
    "docs/smart-contracts/references/crypto-primitives": "/technical-reference/smart-contracts/crypto-primitives.html",
    "docs/smart-contracts/references/host-fns": "/technical-reference/smart-contracts/host-fns.html",
    "docs/smart-contracts/references/local-settings": "/technical-reference/smart-contracts/local-settings.html",
    "docs/smart-contracts/references/references-on-chain": "/technical-reference/smart-contracts/references-on-chain.html",
    "docs/smart-contracts/references/schema-json": "/technical-reference/smart-contracts/schema-json.html",
    "docs/smart-contracts/references/simulate-context": "/technical-reference/smart-contracts/simulate-context.html",
    "tools/grpc2": "/technical-reference/api.html",
    "tools/developer-tools": "/technical-reference/auxiliary-tools.html",
    "tools/concordium-client": "/technical-reference/concordium-client/concordium-client.html",
    "tools/query-node": "/technical-reference/concordium-client/query-node.html",
    "tools/multi-sig": "/technical-reference/concordium-client/multi-sig.html",
    "tools/transactions": "/technical-reference/concordium-client/transactions.html",
    "tools/ccd-scan/ccd-scan": "/technical-reference/ccd-scan/ccd-scan.html",
    "tools/ccd-scan/ccd-scan-blocks": "/technical-reference/ccd-scan/ccd-scan-blocks.html",
    "tools/ccd-scan/ccd-scan-transactions": "/technical-reference/ccd-scan/ccd-scan-transactions.html",
    "tools/ccd-scan/ccd-scan-accounts": "/technical-reference/ccd-scan/ccd-scan-accounts.html",
    "tools/ccd-scan/ccd-scan-staking": "/technical-reference/ccd-scan/ccd-scan-staking.html",
    "tools/ccd-scan/ccd-scan-nodes": "/technical-reference/ccd-scan/ccd-scan-nodes.html",
    "docs/voting/coordinator": "/technical-reference/coordinator.html",
    "technical-reference/governance": "/technical-reference/index.html",
    "docs/release-notes/release-notes-lp": "/technical-reference/release-notes.html",
    "docs/resources/glossary": "/technical-reference/glossary.html",
    "docs/network/baker-pool": "/learn/staking/how-to-become-a-validator.html",
    "docs/network/nodes/node-requirements": "/how-to/nodes/node-requirements.html",
    "docs/network/nodes/run-node-ubuntu/index": "/how-to/nodes/run-node-ubuntu/index.html",
    "docs/network/nodes/run-node-ubuntu/run-node-ubuntu": "/how-to/nodes/run-node-ubuntu/run-node-ubuntu.html",
    "docs/network/nodes/run-node-ubuntu/advanced-node-configuration-on-ubuntu": "/how-to/nodes/run-node-ubuntu/advanced-node-configuration-on-ubuntu.html",
    "docs/network/nodes/run-node-ubuntu/troubleshoot-node-ubuntu": "/how-to/nodes/run-node-ubuntu/troubleshoot-node-ubuntu.html",
    "docs/network/nodes/run-node-docker/index": "/how-to/nodes/run-node-docker/index.html",
    "docs/network/nodes/run-node-docker/run-node-docker": "/how-to/nodes/run-node-docker/run-node-docker.html",
    "docs/network/nodes/run-node-docker/advanced-node-configuration-on-docker": "/how-to/nodes/run-node-docker/advanced-node-configuration-on-docker.html",
    "docs/network/nodes/run-node-docker/troubleshoot-docker": "/how-to/nodes/run-node-docker/troubleshoot-docker.html",
    "docs/network/nodes/run-node-macos/index": "/how-to/nodes/run-node-macos/index.html",
    "docs/network/nodes/run-node-macos/run-node-macos": "/how-to/nodes/run-node-macos/run-node-macos.html",
    "docs/network/nodes/run-node-macos/advanced-node-configuration-on-macos": "/how-to/nodes/run-node-macos/advanced-node-configuration-on-macos.html",
    "docs/network/nodes/run-node-macos/troubleshoot-macos": "/how-to/nodes/run-node-macos/troubleshoot-macos.html",
    "docs/network/nodes/run-node-windows/index": "/how-to/nodes/run-node-windows/index.html",
    "docs/network/nodes/run-node-windows/run-node-windows": "/how-to/nodes/run-node-windows/run-node-windows.html",
    "docs/network/nodes/run-node-windows/advanced-node-configuration-on-windows": "/how-to/nodes/run-node-windows/advanced-node-configuration-on-windows.html",
    "docs/network/nodes/run-node-windows/node-runner-service-configuration": "/how-to/nodes/run-node-windows/node-runner-service-configuration.html",
    "docs/network/nodes/run-node-windows/troubleshoot-windows": "/how-to/nodes/run-node-windows/troubleshoot-windows.html",
    "docs/network/nodes/run-node-aws/index": "/how-to/nodes/run-node-aws/index.html",
    "docs/network/nodes/run-node-aws/run-node-aws": "/how-to/nodes/run-node-aws/run-node-aws.html",
    "docs/network/guides/run-local-chain/index": "/how-to/nodes/run-local-chain/index.html",
    "docs/network/guides/run-local-chain/run-local-chain-docker": "/how-to/nodes/run-local-chain/run-local-chain-docker.html",
    "docs/network/guides/run-local-chain/run-local-chain-source": "/how-to/nodes/run-local-chain/run-local-chain-source.html",
    "docs/network/web3-id/index": "/how-to/web3-id/index.html",
    "docs/network/web3-id/issuer": "/how-to/web3-id/issuer.html",
    "docs/network/web3-id/id-attributes-reference": "/technical-reference/id-attributes-reference.html",
    "docs/network/web3-id/identity-provider-interfaces": "/technical-reference/identity-provider-interfaces.html",
    "docs/network/web3-id/concordia": "/how-to/web3-id/index.html",
    "docs/network/guides/create-proofs": "/how-to/web3-id/create-proofs.html",
    "docs/network/indexers/intro": "/docs/index.html",
    "docs/network/indexers/subquery": "/docs/index.html",
    "docs/smart-contracts/best-practices/index": "/how-to/smart-contracts/best-practices/index.html",
    "docs/smart-contracts/best-practices/costs": "/how-to/smart-contracts/best-practices/costs.html",
    "docs/smart-contracts/best-practices/development": "/how-to/smart-contracts/best-practices/development.html",
    "community/index": "/docs/index.html",
    "community/devnet/devnet": "/docs/index.html",
    "community/devnet/p9-devnet": "/docs/index.html",
    "community/devnet/p10-devnet": "/docs/index.html",
    "community/developer-spotlight/index": "/docs/index.html",
    "community/developer-spotlight/aesirx/index": "/docs/index.html",
    "community/developer-spotlight/edubuk/index": "/docs/index.html",
    "community/developer-spotlight/panenkafc/index": "/docs/index.html",
    "community/developer-spotlight/provenance-tags/index": "/docs/index.html",
    "community/office-hours/index": "/docs/index.html",
    "net/references/developer-tools": "/technical-reference/auxiliary-tools.html",
    "net/guides/dapp-examples": "/tutorials/daap-examples/dapp-examples.html",
    "net/guides/wallets-lp": "/docs/guides/wallets-lp.html",
    "net/guides/wallets-faqs": "/docs/guides/wallets-faqs.html",
    "net/guides/wallets-deciding-wallets": "/docs/guides/deciding-wallets.html",
    "net/guides/cryptox-faq": "/docs/guides/cryptox-faq.html",
    "net/mobile-wallet-gen2/faq": "/docs/guides/mobule-wallet-gen2/faq.html",
    "net/browser-wallet/browser-wallet-faq": "/docs/browser-wallet/browser-wallet-faq.html",
    "net/concepts/concepts-transactions": "/docs/protocol/transactions.html",
    "net/guides/developer-page": "/technical-reference/index.html",
    "net/mobile-wallet-gen2/setup-mobile-wallet": "/docs/guides/setup-cryptox-wallet.html",
    "smart-contracts/guides/setup-tools": "/docs/smart-contracts/guides/setup-contract.html",
    "smart-contracts/guides/build-schema": "/docs/smart-contracts/guides/build-schema.html",
    "smart-contracts/guides/contract-dev-guides": "/how-to/smart-contracts/build-contract.html",
    "smart-contracts/guides/quick-start": "/docs/smart-contracts/guides/quick-start.html",
    "smart-contracts/tutorials/index": "/tutorials/index.html",
    "docs/protocol/id.accounts": "/docs/protocol/id-accounts.html",
    "net/browser-wallet/setup-browser-wallet": "/docs/browser-wallet/setup-browser-wallet.html",
    "net/guides/shield-ccd-wallets": "/docs/guides/shield-ccd-wallets.html",
    "smart-contracts/guides/integration-test-contrac": "/docs/smart-contracts/guides/integration-test-contract.html",
    "net/guides/deciding-wallet": "/docs/guides/deciding-wallet.html",
    "net/resources/terms-and-conditions-mw.": "/docs/index.html",
    "net/guides/add-delegation": "/docs/guides/add-delegation.html",
    "smart-contracts/general/introduction": "/learn/smart-contracts/index.html",
    "net/guides/setup-wallets-lp": "/docs/guides/setup-wallets-lp.html",
    "smart-contracts/best-practices/development": "/docs/smart-contracts/best-practices/development.html",
    "net/guides/overview-desktop": "/docs/guides/overview-desktop.html",
    "net/guides/recovery": "/docs/guides/recovery.html",
    "net/resources/ar-idp-contact": "/docs/index.html",
    "net/guides/new-to-concordium": "/docs/index.html",
    "smart-contracts/guides/unit-test-contract": "/docs/smart-contracts/guides/unit-test-contract.html",
    "smart-contracts/onboarding-guide-ethereum-developers/faq": "/docs/help-and-faq/onboarding-guide-ethereum-developers/faq.html",
    "net/mobile-wallet/share-address-mw":"/docs/mobile-wallet/share-address-mw.html",
    "net/index": "/docs/index.html",
    "net/guides/graviton-hackathon": "/docs/index.html",
    "smart-contracts/onboarding-guide-ethereum-developers": "/docs/help-and-faq/onboarding-guide-ethereum-developers/faq.html",
    "smart-contracts/best-practices": "/docs/smart-contracts/best-practices/index.html",
    "smart-contracts/references/schema-json.html": "/docs/index.html",
    "net/guides/create-identity": "/docs/guides/create-identity.html",
    "smart-contracts/onboarding-guide-solana-developers": "/docs/help-and-faq/onboarding-guide-solana-developers/overview.html",
    "net/mobile-wallet/setup-mobile-wallet": "/docs/guides/setup-cryptox-wallet.html",
    "net/guides/show-seed-phrase": "/docs/guides/show-seed-phrase.html",
    "net/snippets/delegation-faq": "/docs/help-and-faq/delegation-faq.html",
    "net/snippets": "/docs/index.html",
    "smart-contracts/onboarding-guide-solana-developers/overview": "/docs/help-and-faq/onboarding-guide-solana-developers/overview.html",
    "net/guides/export-import": "/docs/guides/export-import.html",
    "net/desktop-wallet/add-delegation": "/docs/guides/add-delegation.html",
    "smart-contracts/general": "/learn/smart-contracts/index.html",
    "smart-contracts/guides/": "/docs/smart-contracts/introduction.html",
    "net/voting": "/docs/voting/gc-voting.html",
    "net": "/docs/index.html",
    "net/release-notes": "/docs/release-notes/release-notes-lp.html",
    "net/nodes": "/docs/network/nodes/node-requirements.html",
    "smart-contracts": "/learn/smart-contracts/index.html",
    "net/references": "/docs/index.html",
    "net/installation": "/docs/installation/downloads.html",
    "net/mobile-wallet": "/docs/guides/wallet-faqs.html",
    "net/guides/wallet-sdk": "/how-to/integrations/wallet-sdk/wallet-sdk.html",
    "net/guides": "/docs/index.html",
    "net/concepts": "/docs/index.html",
    "./en": "/docs/index.html",
    "./en/testnet4/smart-contracts/index": "/docs/index.html",
    "./en/testnet/net/concepts/concepts": "/docs/index.html",
    "./en/testnet/net/index": "/docs/index.html",
    "./en/testnet4/testnet/see-also/troubleshooting.html": "/docs/index.html",
    "./testnet/docs/queries": "/docs/index.html",
    "./testnet/docs/quickstart-wallet": "/docs/index.html",
    "./en/testnet": "/docs/index.html",
    "./en/testnet4/testnet/index": "/docs/index.html",
    "./en/testnet4": "/docs/index.html",
    "./testnet/docs/client": "/docs/index.html",
    "./testnet/docs/identities-and-accounts": "/docs/index.html",
    "./testnet/docs/quickstart-node": "/docs/index.html",
    "./testnet/docs/nonces": "/docs/index.html",
    "./testnet/docs/linux": "/docs/index.html",
    "./testnet/docs/downloads": "/docs/installation/downloads.html",
    "./testnet/docs/troubleshooting": "/docs/index.html",
    "./testnet/docs/transactions": "/docs/protocol/transactions.html",
    "./en/testnet4/testnet/see-also/release-notes": "/docs/release-notes/release-notes.html",
    "./testnet/docs/webwallet": "/docs/browser-wallet/browser-wallet-faq.html",
    "./testnet": "/docs/index.html",
    "./en/testnet4/smart-contracts": "/docs/index.html",
    "./testnet/docs/windows": "/docs/index.html",
    "./en/testnet/net": "/docs/index.html",
    "./en/testnet4/testnet/see-also": "/docs/index.html",
    "./testnet/docs/managing-accounts": "/docs/protocol/manage-accounts.html",
    "./en/testnet4/testnet": "/docs/index.html",
    "./testnet/docs/macos": "/docs/index.html",
    "./testnet/docs/quickstart-baker": "/docs/index.html",
    "./governance/whitepaper":"/docs/index.html",
    "./governance/rules": "/docs/index.html",
    "./governance/foundation": "/docs/index.html",
    "./governance": "/docs/index.html",
    "./concordium-node-sdk-js/pages/misc-pages/grpc-v1.md": "/docs/index.html",
    "./classes/grpc.ConcordiumGRPCClient": "/docs/index.html",
    "./concordium-net-sdk/api/Concordium.Grpc": "/docs/index.html",
    "./concordium-node-sdk-js/classes": "/docs/index.html",
    "./concordium-node-sdk-js/modules/Common_GRPC_Client": "/docs/index.html",
    "./concordium-node-sdk-js/pages": "/docs/index.html",
    "./concordium-node-sdk-js/pages/misc-pages": "/docs/index.html",
    "./concordium-net-sdk/api/Concordium.Sdk": "/docs/index.html",
    "./concordium-net-sdk/api/Concordium": "/docs/index.html",
    "net/guides/run-node-aws": "/docs/network/nodes/run-node-aws.html",
    "docs/network/guides/concordium-client" : "/technical-reference/concordium-client/concordium-client.html",
    "tutorials/piggy-bank/wCCD-frontend-set-up" : "/tutorials/piggy-bank/frontend.html",
    "net/resources/bw-licenses" : "/docs/guides/cryptox-terms.html",
    "net/guides/legal" : "/docs/guides/cryptox-terms.html",
    "net/guides/export-key" : "/docs/guides/export-account-private-key.html",
    "smart-contracts/guides/on-chain-index" : "/learn/smart-contracts/index.html",
    "docs/protocol/company-identities" : "/tutorials/company-identity/company-identities.html",
    "docs/network/query-node" : "/technical-reference/concordium-client/query-node.html",
    "net/references/net/references/grpc2" : "/technical-reference/api.html",
    "guides/export-import": "/docs/guides/recovery.html",
    "guides/recover-wallet": "/docs/guides/recovery.html",
    "docs/protocol/id-accounts": "/docs/protocol/identity.html",
    "docs/network/guides/become-baker": "/docs/network/guides/become-validator.html",
    "docs/guides/cryptox-faq": "/docs/guides/concordium-wallet-faq.html",
    "docs/guides/setup-cryptox-wallet": "/docs/guides/setup-concordium-wallet.html",
    "docs/protocol/concordium-protocol": "/learn/concordium-protocol.html",
    "docs/protocol/identity": "/learn/identity/index.html",
    "docs/protocol/principles-of-privacy": "/learn/identity/principles-of-privacy.html",
    "docs/protocol/user-processes": "/learn/identity/user-processes.html",
    "docs/protocol/identity-disclosure-processes": "/learn/identity/identity-disclosure-processes.html",
    "docs/protocol/manage-accounts": "/learn/accounts/index.html",
    "docs/protocol/account-concepts": "/learn/accounts/account-concepts.html",
    "docs/protocol/account-aliases": "/learn/accounts/account-aliases.html",
    "docs/protocol/key-derivation-and-usage": "/learn/accounts/key-derivation-and-usage.html",
    "docs/protocol/transactions": "/learn/transactions/index.html",
    "docs/protocol/transaction-reference": "/learn/transactions/transaction-reference.html",
    "docs/protocol/transaction-fees": "/learn/transactions/transaction-fees.html",
    "docs/protocol/sponsored-transactions": "/learn/transactions/sponsored-transactions.html",
    "docs/protocol/consensus-mechanisms": "/learn/consensus/index.html",
    "docs/protocol/concepts-baker": "/learn/consensus/concepts-baker.html",
    "docs/protocol/time-concepts": "/learn/consensus/time-concepts.html",
    "docs/protocol/validator-suspension": "/learn/consensus/validator-suspension.html",
    "docs/protocol/tokenomics": "/learn/tokenomics.html",
    "docs/protocol/staking": "/learn/staking/index.html",
    "docs/protocol/concepts-delegation": "/learn/staking/concepts-delegation.html",
    "docs/protocol/how-to-become-a-validator": "/learn/staking/how-to-become-a-validator.html",
    "docs/voting/gc-voting": "/learn/governance/gc-voting.html",
    "docs/network/guides/validation-with-wallets": "/how-to/infrastructure/validation-with-wallets.html",
    "docs/network/guides/become-validator": "/how-to/infrastructure/become-validator.html",
    "docs/network/guides/add-baker-mw": "/how-to/infrastructure/add-baker-mw.html",
    "docs/network/guides/import-validator-keys": "/how-to/infrastructure/import-validator-keys.html",
    "docs/network/guides/update-baker-mw": "/how-to/infrastructure/update-baker-mw.html",
    "docs/network/guides/suspend-unsuspend-validator": "/how-to/infrastructure/suspend-unsuspend-validator.html",
    "docs/network/guides/stop-validator": "/how-to/infrastructure/stop-validator.html",
    "docs/voting/voting": "/how-to/governance/voting.html",
    "docs/voting/guardians": "/how-to/governance/guardians.html",
    "docs/voting/verify-election-result": "/how-to/governance/verify-election-result.html",
    "docs/resources/exchangeOnBoarding": "/how-to/integrations/exchange-onboarding.html",
    "docs/smart-contracts/guides/setup-contract": "/how-to/smart-contracts/setup-contract.html",
    "docs/smart-contracts/guides/compile-module": "/how-to/smart-contracts/compile-module.html",
    "docs/smart-contracts/guides/build-schema": "/how-to/smart-contracts/build-schema.html",
    "docs/smart-contracts/guides/no-std": "/how-to/smart-contracts/no-std.html",
    "docs/smart-contracts/guides/fallback-entrypoints": "/how-to/smart-contracts/fallback-entrypoints.html",
    "docs/smart-contracts/guides/upgradeable-contract": "/how-to/smart-contracts/upgradeable-contract.html",
    "docs/smart-contracts/guides/migrate-contracts": "/how-to/smart-contracts/migrate-contracts.html",
    "docs/smart-contracts/guides/unit-test-contract": "/how-to/smart-contracts/unit-test-contract.html",
    "docs/smart-contracts/guides/integration-test-contract": "/how-to/smart-contracts/integration-test-contract.html",
    "docs/smart-contracts/guides/quick-start": "/tutorials/quick-start.html",
    "docs/smart-contracts/introduction": "/learn/smart-contracts/index.html",
    "docs/smart-contracts/contract-lifecycle": "/learn/smart-contracts/contract-lifecycle.html",
    "docs/smart-contracts/contract-module": "/learn/smart-contracts/contract-module.html",
    "docs/smart-contracts/contract-instances": "/learn/smart-contracts/contract-instances.html",
    "docs/smart-contracts/contract-schema": "/learn/smart-contracts/contract-schema.html",
    "docs/smart-contracts/develop-contracts": "/learn/smart-contracts/develop-contracts.html",
    "docs/smart-contracts/guides/build-contract": "/how-to/smart-contracts/build-contract.html",
    "docs/smart-contracts/guides/deploy-module": "/how-to/smart-contracts/deploy-module.html",
    "docs/smart-contracts/guides/initialize-contract": "/how-to/smart-contracts/initialize-contract.html",
    "docs/smart-contracts/guides/interact-instance": "/how-to/smart-contracts/interact-instance.html",
    "docs/smart-contracts/guides/inspect-instance": "/how-to/smart-contracts/inspect-instance.html",
    "docs/smart-contracts/guides/invoke-instance": "/how-to/smart-contracts/invoke-instance.html",
    "docs/smart-contracts/guides/custom-errors": "/how-to/smart-contracts/custom-errors.html",
    "docs/smart-contracts/guides/json-params": "/how-to/smart-contracts/json-params.html",
    "docs/smart-contracts/guides/factory-pattern": "/how-to/smart-contracts/factory-pattern.html",
    "docs/concordium-id/verify-and-access/index": "/how-to/concordium-id/verify-and-access/index.html",
    "docs/concordium-id/verify-and-access/how-it-works": "/how-to/concordium-id/verify-and-access/how-it-works.html",
    "docs/concordium-id/verify-and-access/select-verification-method": "/how-to/concordium-id/verify-and-access/select-verification-method.html",
    "docs/concordium-id/verify-and-access/select-identity-provider": "/how-to/concordium-id/verify-and-access/select-identity-provider.html",
    "docs/concordium-id/verify-and-access/manage-transaction-costs": "/how-to/concordium-id/verify-and-access/manage-transaction-costs.html",
    "docs/concordium-id/verify-and-access/integrate-verification-flow": "/how-to/concordium-id/verify-and-access/integrate-verification-flow.html",
    "docs/concordium-id/verify-and-access/access-the-concordium-network": "/how-to/concordium-id/verify-and-access/access-the-concordium-network.html",
    "docs/integration/wallet integration/wallet-integration": "/how-to/integrations/wallet-integration/wallet-integration.html",
    "docs/integration/wallet integration/integrating-identity-layer": "/how-to/integrations/wallet-integration/integrating-identity-layer.html",
    "docs/integration/wallet integration/supporting-zero-knowledge-proofs": "/how-to/integrations/wallet-integration/supporting-zero-knowledge-proofs.html",
    "docs/integration/wallet integration/supporting-transactions": "/how-to/integrations/wallet-integration/supporting-transactions.html",
    "docs/integration/wallet integration/supporting-staking": "/how-to/integrations/wallet-integration/supporting-staking.html",
    "docs/integration/wallet integration/connecting-wallet-to-network": "/how-to/integrations/wallet-integration/connecting-wallet-to-network.html",
    "docs/integration/x402 integration/x402-integration": "/how-to/integrations/x402-integration.html",
    "docs/guides/account-activities-lp": "/technical-reference/wallets/guides/account-activities-lp.html",
    "docs/guides/add-delegation": "/technical-reference/wallets/guides/add-delegation.html",
    "docs/guides/address-book": "/technical-reference/wallets/guides/address-book.html",
    "docs/guides/change-account-name": "/technical-reference/wallets/guides/change-account-name.html",
    "docs/guides/change-identity-name": "/technical-reference/wallets/guides/change-identity-name.html",
    "docs/guides/concordium-wallet-faq": "/technical-reference/wallets/guides/concordium-wallet-faq.html",
    "docs/guides/create-account": "/technical-reference/wallets/guides/create-account.html",
    "docs/guides/create-identity": "/technical-reference/wallets/guides/create-identity.html",
    "docs/guides/cryptox-terms": "/technical-reference/wallets/guides/cryptox-terms.html",
    "docs/guides/deciding-wallet": "/technical-reference/wallets/guides/deciding-wallet.html",
    "docs/guides/export-account-private-key": "/technical-reference/wallets/guides/export-account-private-key.html",
    "docs/guides/export-transaction-logs": "/technical-reference/wallets/guides/export-transaction-logs.html",
    "docs/guides/import-export-file": "/technical-reference/wallets/guides/import-export-file.html",
    "docs/guides/ledger-tutorial": "/technical-reference/wallets/guides/ledger-tutorial.html",
    "docs/guides/manage-wallets-lp": "/technical-reference/wallets/guides/manage-wallets-lp.html",
    "docs/guides/multi-credentials": "/technical-reference/wallets/guides/multi-credentials.html",
    "docs/guides/multisig-transfer": "/technical-reference/wallets/guides/multisig-transfer.html",
    "docs/guides/overview-desktop": "/technical-reference/wallets/guides/overview-desktop.html",
    "docs/guides/overview-shared-accounts": "/technical-reference/wallets/guides/overview-shared-accounts.html",
    "docs/guides/proofs": "/technical-reference/wallets/guides/proofs.html",
    "docs/guides/recovery": "/technical-reference/wallets/guides/recovery.html",
    "docs/guides/remove-delegation": "/technical-reference/wallets/guides/remove-delegation.html",
    "docs/guides/scheduled-release": "/technical-reference/wallets/guides/scheduled-release.html",
    "docs/guides/send-ccd-wallets": "/technical-reference/wallets/guides/send-ccd-wallets.html",
    "docs/guides/setup-concordium-wallet": "/technical-reference/wallets/guides/setup-concordium-wallet.html",
    "docs/guides/setup-wallets-lp": "/technical-reference/wallets/guides/setup-wallets-lp.html",
    "docs/guides/shield-ccd-wallets": "/technical-reference/wallets/guides/shield-ccd-wallets.html",
    "docs/guides/show-seed-phrase": "/technical-reference/wallets/guides/show-seed-phrase.html",
    "docs/guides/show-wallet-private-key": "/technical-reference/wallets/guides/show-wallet-private-key.html",
    "docs/guides/tokens": "/technical-reference/wallets/guides/tokens.html",
    "docs/guides/transaction-report": "/technical-reference/wallets/guides/transaction-report.html",
    "docs/guides/update-delegation": "/technical-reference/wallets/guides/update-delegation.html",
    "docs/guides/wallet": "/technical-reference/wallets/guides/wallet.html",
    "docs/guides/wallet-faqs": "/technical-reference/wallets/guides/wallet-faqs.html",
    "docs/guides/wallets-lp": "/technical-reference/wallets/guides/wallets-lp.html",
    "docs/desktop-wallet/accounts-desktop": "/technical-reference/wallets/desktop-wallet/accounts-desktop.html",
    "docs/desktop-wallet/create-credentials-file": "/technical-reference/wallets/desktop-wallet/create-credentials-file.html",
    "docs/desktop-wallet/dw-lp": "/technical-reference/wallets/desktop-wallet/dw-lp.html",
    "docs/desktop-wallet/install-ledger-app": "/how-to/governance/install-ledger-app.html",
    "docs/desktop-wallet/multisig-simple-transfer": "/technical-reference/wallets/desktop-wallet/multisig-simple-transfer.html",
    "docs/desktop-wallet/proposed-transactions": "/technical-reference/wallets/desktop-wallet/proposed-transactions.html",
    "docs/desktop-wallet/reset-data": "/technical-reference/wallets/desktop-wallet/reset-data.html",
    "docs/desktop-wallet/sign-transaction": "/technical-reference/wallets/desktop-wallet/sign-transaction.html",
    "docs/desktop-wallet/single-sign-schedule": "/technical-reference/wallets/desktop-wallet/single-sign-schedule.html",
    "docs/desktop-wallet/transaction-log-filter": "/technical-reference/wallets/desktop-wallet/transaction-log-filter.html",
    "docs/desktop-wallet/update-application": "/technical-reference/wallets/desktop-wallet/update-application.html",
    "docs/help-and-faq/delegation-faq": "/how-to/infrastructure/delegation-faq.html",
    "docs/installation/downloads": "/downloads.html",
    "docs/help-and-faq/set-up-doc-env": "/docs/index.html",
    "docs/help-and-faq/style-guide": "/docs/index.html",
    "docs/help-and-faq/onboarding-guide-ethereum-developers/faq": "/docs/index.html",
    "docs/help-and-faq/onboarding-guide-solana-developers/overview": "/docs/index.html",
    "docs/help-and-faq/onboarding-guide-solana-developers/faq": "/docs/index.html",
    "docs/help-and-faq/faqs": "/docs/index.html",
    "docs/plt/index": "/tutorials/plt/index.html",
    "docs/plt/setup-guide/index": "/tutorials/plt/setup-guide.html",
    "docs/plt/setup-guide/request-ccd": "/tutorials/plt/request-ccd.html",
    "docs/plt/setup-guide/request-plt": "/tutorials/plt/request-plt.html",
    "docs/plt/operations/index": "/tutorials/plt/operations.html",
    "docs/plt/examples/index": "/tutorials/plt/examples.html",
    "docs/plt/examples/concordium-client": "/tutorials/plt/concordium-client.html",
    "docs/plt/examples/web-sdk": "/tutorials/plt/web-sdk.html",
    "docs/plt/examples/rust-sdk": "/tutorials/plt/rust-sdk.html",
    "docs/plt/setup-guide/account-creation": "/tutorials/plt/index.html",
    "docs/plt/setup-guide/browser-wallet": "/tutorials/plt/index.html",
    "docs/plt/setup-guide/devnet-connection": "/tutorials/plt/index.html",
    "docs/plt/setup-guide/identity-creation": "/tutorials/plt/index.html",
    "tutorials/integrating-concordium": "/tutorials/index.html"
    }
